### ISSUE TITLE
Assign DataFrame instead of reading it

### ISSUE THREAD

**Issue by ahnt** [VincentRagusa/DDIT#1]
Not really an issue per se, since I can always save a DataFrame and then load it, but is there a way (or could there be a way) to assign a DataFrame (including the header) instead of just loading it?
Cheers Arend

**Comment by VincentRagusa** [comment]
Arend,
DDIT does not currently support working with pandas DataFrames. You can, however, use the register_column_list() method to register any python list object as a random variable. Pandas should support extracting a column as a list object which you could pipe into DDIT via the above method.
